### ISSUE TITLE
Change Opacity of each step individually

### ISSUE THREAD

**Issue by holli77** [impress/impress.js#451]
Hey there,

is there a possibility to change the opacity of each inactive step individually?
For example if I'm in step-1 that step-2 and 3 are transparent and step-4 is visible again.

Replace the following part, step by step?:

![opacity](https://cloud.githubusercontent.com/assets/8360489/5718554/745445ac-9b0f-11e4-84e4-773fe270d10c.PNG)

**Comment by FagnerMartinsBrack** [comment]
Just use the appropriate selector for each individual step with a greater specificity:

```css
.impress-enabled .step {
   /* original styles */
}

.impress-enabled .step.my-custom-step {
   transition: opacity .5s;
}

.impress-enabled .step.active { opacity: 1; }
```

Or tie with the order of the rules in the file, then you don't need to change specificity:

```css
.impress-enabled .step {
   /* original styles */
}

<!-- This should stay always below the generic rule for all steps -->
.impress-enabled .my-custom-step {
   transition: opacity .5s;
}

.impress-enabled .step.active { opacity: 1; }
```

`.impress-enabled .step.active` doesn't need to be changed.

I didn't tested anything, but this may be useful to get started.
