### ISSUE TITLE
impressConsole: View end Preview iframes not scaled correctly for large presentation widths

### ISSUE THREAD

**Issue by tobias-hd** [impress/impress.js#692]
The impressConsole seems not to scale down correctly the content of the slideView and preView iframes, when the width of the slides is larger than the default 900px.

I have a presentation for a screen width of 1920x1080px, for which I have set the slide width to 1700px:

```css
.step {
    position: relative;
    width: 1700px;
    /* ... */
}
.slide {
    width: 1700px;
    height: 1000px;
    /* ... */
}
```

When I open the impress console, both the content of slideView end preView is not fully visible, since it's not scaled down sufficiently.

I tried to scale down the iframe with:
```css
iframe#slideView div#impress {
  transform: scale(0.46);
} 
```
but this does not work - maybe it's just incorrect css, or the wrong place to do it (default css file)

Any ideas how to fix this?
Thanks, 
Tobias
